-- FUNCTION PARA OBTENER EL HISTORIAL COMPLETO DE UN USUARIO
CREATE OR REPLACE FUNCTION fn_user_historial(ID_RUT INT, ID_DV INT)
RETURNS TABLE(
	NOMBRE_COMPLETO	VARCHAR(255),
	RUT 			VARCHAR(20),
	PREVISION		VARCHAR(50),
	FECHA_DE_NACIMIENTO VARCHAR(20),
	NACIONALIDAD	VARCHAR(25),
	DOMICILIO 		TEXT,
	TELEFONO		VARCHAR(20),
	FECHA_PAP	 	VARCHAR(20),
	INDICACIONES	TEXT,
	RESULTADO_PAP	TEXT,
	MOTIVO_PAP		VARCHAR(100),
	ID_HISTORIAL	BIGINT
) 
LANGUAGE PLPGSQL
AS $$
	DECLARE
	OUTPUT_CURSOR RECORD;
		BEGIN
			FOR OUTPUT_CURSOR IN(
				
				SELECT	CONCAT(MAT_USER.USER_NOMBRES,' ', MAT_USER.USER_APELLIDO_PATERNO, ' ', MAT_USER.USER_APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
						CONCAT(MAT_USER.USER_RUT_SIN_DV,'-', MAT_USER.USER_RUT_DV) AS RUT,
						MAT_HISTORIAL.MAT_HISTORIAL_PK AS ID_HISTORIAL,
					    MAT_USER.USER_PREVISION AS PREVISION,
						TO_CHAR(MAT_USER.USER_FECHA_NACIMIENTO, 'DD-MM-YYYY') AS FECHA_DE_NACIMIENTO,
						MAT_USER.USER_NACIONALIDAD AS NACIONALIDAD,
						MAT_USER.USER_DIRECCION AS DOMICILIO,
						CONCAT('+56',MAT_USER.USER_TELEFONO) AS TELEFONO,
						TO_CHAR(MAT_HISTORIAL.MAT_HISTORIAL_FECHA_PAP, 'DD-MM-YYYY') AS FECHA_PAP,
						MAT_HISTORIAL.MAT_HISTORIAL_INDICACIONES AS INDICACIONES,
						MAT_HISTORIAL.MAT_HISTORIAL_RESULTADO_PAP AS RESULTADO_PAP,
						MAT_HISTORIAL.MAT_HISTORIAL_MOTIVO_PAP AS MOTIVO_PAP
				FROM _MATRONAS_USER AS MAT_USER
				INNER JOIN _MATRONAS_HISTORIAL AS MAT_HISTORIAL
				ON MAT_USER.USER_RUT_SIN_DV = MAT_HISTORIAL.USER_RUT_SIN_DV
				WHERE MAT_USER.USER_RUT_SIN_DV = ID_RUT --ID_RUT
				AND	MAT_USER.USER_RUT_DV = CAST(ID_DV AS VARCHAR) --ID_DV
				
			) LOOP 	NOMBRE_COMPLETO	:= OUTPUT_CURSOR.NOMBRE_COMPLETO;
				RUT 				:= OUTPUT_CURSOR.RUT;
				PREVISION 			:= OUTPUT_CURSOR.PREVISION;
				FECHA_DE_NACIMIENTO	:= OUTPUT_CURSOR.FECHA_DE_NACIMIENTO;
				NACIONALIDAD 		:= OUTPUT_CURSOR.NACIONALIDAD;
				DOMICILIO 			:= OUTPUT_CURSOR.DOMICILIO;
				TELEFONO 			:= OUTPUT_CURSOR.TELEFONO;
				FECHA_PAP			:= OUTPUT_CURSOR.FECHA_PAP;
				INDICACIONES		:= OUTPUT_CURSOR.INDICACIONES;
				RESULTADO_PAP		:= OUTPUT_CURSOR.RESULTADO_PAP;
				MOTIVO_PAP			:= OUTPUT_CURSOR.MOTIVO_PAP;
				ID_HISTORIAL		:= OUTPUT_CURSOR.ID_HISTORIAL;
			RETURN NEXT;
		END LOOP;
END; $$

-- VISUALIZACION LISTA
CREATE OR REPLACE FUNCTION fn_user_principal()
RETURNS TABLE(
	NOMBRE_COMPLETO	VARCHAR(255),
	RUT 			VARCHAR(20),
	FECHA_PAP		DATE,
	VIGENCIA_PAP   	DATE,
	--RUT_MATRONA	VARCHAR(25), FALTA MODIFICAR LAS TABLAS Y LOS PROCESOS PARA PODER INCLUIR EL RUT DE DEL USUARIO QUE HACE EL INGRESO
	ID_USUARIO		BIGINT
) 
LANGUAGE PLPGSQL
AS $$
	DECLARE
	OUTPUT_CURSOR RECORD;
		BEGIN
			FOR OUTPUT_CURSOR IN(
				
				SELECT	CONCAT(MAT_USER.USER_NOMBRES,' ', MAT_USER.USER_APELLIDO_PATERNO, ' ', MAT_USER.USER_APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
						CONCAT(MAT_USER.USER_RUT_SIN_DV,'-', MAT_USER.USER_RUT_DV) AS RUT,
						(
							SELECT 
						 		MAX(MAT_HISTORIAL_FECHA_PAP) 
							FROM _MATRONAS_HISTORIAL
							WHERE USER_RUT_SIN_DV = MAT_USER.USER_RUT_SIN_DV
							AND USER_RUT_DV = MAT_USER.USER_RUT_DV
						) AS FECHA_PAP,
						(
							SELECT 
								MAX(MAT_HISTORIAL_VIGENCIA_PAP) 
							FROM _MATRONAS_HISTORIAL 
							WHERE USER_RUT_SIN_DV = MAT_USER.USER_RUT_SIN_DV
							AND USER_RUT_DV = MAT_USER.USER_RUT_DV
						) AS VIGENCIA_PAP,
						MAT_USER.USER_PK AS ID_USUARIO
				FROM _MATRONAS_USER AS MAT_USER
				
			) LOOP 	NOMBRE_COMPLETO		:= OUTPUT_CURSOR.NOMBRE_COMPLETO;
					RUT 				:= OUTPUT_CURSOR.RUT;
					FECHA_PAP 			:= OUTPUT_CURSOR.FECHA_PAP;
					VIGENCIA_PAP		:= OUTPUT_CURSOR.VIGENCIA_PAP;
					ID_USUARIO 			:= OUTPUT_CURSOR.ID_USUARIO;
					--RUT_MATRONA 			:= OUTPUT_CURSOR.RUT_MATRONA;
			RETURN NEXT;
		END LOOP;
END; $$


select * from fn_user_historial(18028144,4)
select * from fn_user_principal()