-- FUNCTION PARA OBTENER EL HISTORIAL COMPLETO DE UN USUARIO
CREATE OR REPLACE FUNCTION fn_user_historial(ID_RUT INT, ID_DV INT)
RETURNS TABLE(
	NOMBRE_COMPLETO	VARCHAR(255),
	RUT 			VARCHAR(20),
	PREVISION		VARCHAR(50),
	FECHA_DE_NACIMIENTO VARCHAR(20),
	NACIONALIDAD	VARCHAR(25),
	DOMICILIO 		TEXT,
	TELEFONO		VARCHAR(20),
	FECHA_PAP	 	VARCHAR(20),
	INDICACIONES	TEXT,
	OBSERVACIONES	TEXT,
	MOTIVO_PAP		VARCHAR(100)
) 
LANGUAGE PLPGSQL
AS $$
	DECLARE
	OUTPUT_CURSOR RECORD;
		BEGIN
			FOR OUTPUT_CURSOR IN(
				
				SELECT	CONCAT(MAT_USER.USER_NOMBRES,' ', MAT_USER.USER_APELLIDO_PATERNO, ' ', MAT_USER.USER_APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
						CONCAT(MAT_USER.USER_RUT_SIN_DV,'-', MAT_USER.USER_RUT_DV) AS RUT,						
				CASE 
					WHEN (MAT_USER.USER_PREVISION IS NULL) 
					THEN 'SIN PREVISION'	
				END AS PREVISION,
						TO_CHAR(MAT_USER.USER_FECHA_NACIMIENTO, 'DD-MM-YYYY') AS FECHA_DE_NACIMIENTO,
				CASE
					WHEN (MAT_USER.USER_NACIONALIDAD IS NULL)
					THEN 'SIN NACIONALIDAD'
				END AS NACIONALIDAD,
						MAT_USER.USER_DIRECCION AS DOMICILIO,
						CONCAT('+56',MAT_USER.USER_TELEFONO) AS TELEFONO,
						TO_CHAR(MAT_HISTORIAL.MAT_HISTORIAL_FECHA_PAP, 'DD-MM-YYYY') AS FECHA_PAP,
						MAT_HISTORIAL.MAT_HISTORIAL_INDICACIONES AS INDICACIONES,
						MAT_HISTORIAL.MAT_HISTORIAL_OBSERVACIONES AS OBSERVACIONES,
						MAT_HISTORIAL.MAT_HISTORIAL_MOTIVO_PAP AS MOTIVO_PAP
				FROM _MATRONAS_USER AS MAT_USER
				INNER JOIN _MATRONAS_HISTORIAL AS MAT_HISTORIAL
				ON MAT_USER.USER_RUT_SIN_DV = MAT_HISTORIAL.USER_RUT_SIN_DV
				WHERE MAT_USER.USER_RUT_SIN_DV = ID_RUT --ID_RUT
				AND	MAT_USER.USER_RUT_DV = CAST(ID_DV AS VARCHAR) --ID_DV
				
			) LOOP 	NOMBRE_COMPLETO	:= OUTPUT_CURSOR.NOMBRE_COMPLETO;
				RUT 				:= OUTPUT_CURSOR.RUT;
				PREVISION 			:= OUTPUT_CURSOR.PREVISION;
				FECHA_DE_NACIMIENTO	:= OUTPUT_CURSOR.FECHA_DE_NACIMIENTO;
				NACIONALIDAD 		:= OUTPUT_CURSOR.NACIONALIDAD;
				DOMICILIO 			:= OUTPUT_CURSOR.DOMICILIO;
				TELEFONO 			:= OUTPUT_CURSOR.TELEFONO;
				FECHA_PAP			:= OUTPUT_CURSOR.FECHA_PAP;
				INDICACIONES		:= OUTPUT_CURSOR.INDICACIONES;
				OBSERVACIONES		:= OUTPUT_CURSOR.OBSERVACIONES;
				MOTIVO_PAP			:= OUTPUT_CURSOR.MOTIVO_PAP;
			RETURN NEXT;
		END LOOP;
END; $$

select * from fn_user_historial(18028144, 4);